#!/bin/bash

action=$1
change=$2

function running_sinks {
  pactl list sinks short | grep -i 'running' | cut -f1
}

function default_sink {
  name=$(pacmd stat | grep -i 'default sink' | awk -F ': *' '{ print $2 }')
  pactl list sinks short | fgrep "$name" | cut -f1
}

function current_volume {
  pulsemixer --get-volume | cut -f1 -d' '
}

function change_volumes {
  local sinks="$1"
  for sink in $sinks; do
    pactl set-sink-volume "$sink" $change
  done
}

function mute_volumes {
  local sinks="$1"
  for sink in $sinks; do
    pactl set-sink-mute "$sink" toggle
  done
}

sinks=$(running_sinks)
if [ -z "$sinks" ]; then
  sinks=$(default_sink)
fi

if [ $action == "s" ]; then
change_volumes "$sinks"
fi

if [ $action == "m" ]; then
  mute_volumes "$sinks"
fi

current_volume "$sink"
